### ISSUE TITLE
Error when attempting to generate images

### ISSUE THREAD

**Issue by Shaistrong** [FizzleDorf/ComfyUI-AIT#12]
I was able to compile some modules again, but when I use the new/old modules I get this error:
`got prompt
unloaded AIT
<ComfyUI-AIT.ait_load.AITPatch object at 0x000001958450E260>
Requested to load SDXL
Loading 1 new model
  0%|                                                                                           | 0/67 [00:00<?, ?it/s][17:25:59] model_interface.cu:123: Error: Called SetConstant on time_embed_0_weight but can't find in either bound or unbound constant set
  0%|                                                                                           | 0/67 [00:00<?, ?it/s]
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "C:\Users\joker\OneDrive\Desktop\A.I\ComfyUI_latest\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\Users\joker\OneDrive\Desktop\A.I\ComfyUI_latest\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\Users\joker\OneDrive\Desktop\A.I\ComfyUI_latest\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\Users\joker\OneDrive\Desktop\A.I\ComfyUI_latest\nodes.py", line 1237, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "C:\Users\joker\OneDrive\Desktop\A.I\ComfyUI_latest\nodes.py", line 1207, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "C:\Users\joker\OneDrive\Desktop\A.I\ComfyUI_latest\custom_nodes\ComfyUI-Impact-Pack\modules\impact\sample_error_enhancer.py", line 22, in informative_sample
    raise e
  File "C:\Users\joker\OneDrive\Desktop\A.I\ComfyUI_latest\custom_nodes\ComfyUI-Impact-Pack\modules\impact\sample_error_enhancer.py", line 9, in informative_sample
    return original_sample(*args, **kwargs)
  File "C:\Users\joker\OneDrive\Desktop\A.I\ComfyUI_latest\comfy\sample.py", line 100, in sample
    samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "C:\Users\joker\OneDrive\Desktop\A.I\ComfyUI_latest\comfy\samplers.py", line 691, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler(), sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "C:\Users\joker\OneDrive\Desktop\A.I\ComfyUI_latest\comfy\samplers.py", line 597, in sample
    samples = sampler.sample(model_wrap, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "C:\Users\joker\OneDrive\Desktop\A.I\ComfyUI_latest\comfy\samplers.py", line 557, in sample
    samples = getattr(k_diffusion_sampling, "sample_{}".format(sampler_name))(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **extra_options)
  File "C:\Users\joker\OneDrive\Desktop\A.I\xformers\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\joker\OneDrive\Desktop\A.I\ComfyUI_latest\comfy\k_diffusion\sampling.py", line 580, in sample_dpmpp_2m
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "C:\Users\joker\OneDrive\Desktop\A.I\xformers\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\joker\OneDrive\Desktop\A.I\xformers\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\joker\OneDrive\Desktop\A.I\ComfyUI_latest\comfy\samplers.py", line 274, in forward
    out = self.inner_model(x, sigma, cond=cond, uncond=uncond, cond_scale=cond_scale, model_options=model_options, seed=seed)
  File "C:\Users\joker\OneDrive\Desktop\A.I\xformers\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\joker\OneDrive\Desktop\A.I\xformers\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\joker\OneDrive\Desktop\A.I\ComfyUI_latest\comfy\samplers.py", line 264, in forward
    return self.apply_model(*args, **kwargs)
  File "C:\Users\joker\OneDrive\Desktop\A.I\ComfyUI_latest\comfy\samplers.py", line 261, in apply_model
    out = sampling_function(self.inner_model.apply_model, x, timestep, uncond, cond, cond_scale, model_options=model_options, seed=seed)
  File "C:\Users\joker\OneDrive\Desktop\A.I\ComfyUI_latest\comfy\samplers.py", line 249, in sampling_function
    cond, uncond = calc_cond_uncond_batch(model_function, cond, uncond, x, timestep, max_total_area, model_options)
  File "C:\Users\joker\OneDrive\Desktop\A.I\ComfyUI_latest\comfy\samplers.py", line 224, in calc_cond_uncond_batch
    output = model_options['model_function_wrapper'](model_function, {"input": input_x, "timestep": timestep_, "c": c, "cond_or_uncond": cond_or_uncond}).chunk(batch_chunks)
  File "C:\Users\joker\OneDrive\Desktop\A.I\ComfyUI_latest\custom_nodes\ComfyUI-AIT\ait_load.py", line 69, in __call__
    self.ait_model.set_weights(sd)
  File "C:\Users\joker\OneDrive\Desktop\A.I\ComfyUI_latest\custom_nodes\ComfyUI-AIT\ait_load.py", line 43, in set_weights
    self.exe_module.set_many_constants_with_tensors(constants)
  File "C:\Users\joker\OneDrive\Desktop\A.I\xformers\lib\site-packages\aitemplate\compiler\model.py", line 861, in set_many_constants_with_tensors
    self.set_many_constants(ait_tensors)
  File "C:\Users\joker\OneDrive\Desktop\A.I\xformers\lib\site-packages\aitemplate\compiler\model.py", line 812, in set_many_constants
    self.DLL.AITemplateModelContainerSetManyConstants(
  File "C:\Users\joker\OneDrive\Desktop\A.I\xformers\lib\site-packages\aitemplate\compiler\model.py", line 196, in _wrapped_func
    raise RuntimeError(f"Error in function: {method.__name__}")
RuntimeError: Error in function: AITemplateModelContainerSetManyConstants

Prompt executed in 2.10 seconds`

**Comment by willpnelson** [comment]
Having the same issue:

File "D:\stable_diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\aitemplate\compiler\model.py", line 196, in _wrapped_func
    raise RuntimeError(f"Error in function: {method.__name__}")
RuntimeError: Error in function: AITemplateModelContainerSetManyConstants

**Comment by FizzleDorf** [comment]
I am assuming you are using 1.x modules. Sdxl works fine it some work needs to be done to get compatability with 1.x modules. Yesterday I can confirm sdxl modules are working as I was testing them with lcm lora (it works with lcm btw!) Just in case, let me know if you can inference with an xl module. Thanks in advance.

**Comment by Shaistrong** [comment]
> I am assuming you are using 1.x modules. Sdxl works fine but some work needs to be done to get compatability with 1.x modules. Yesterday I can confirm sdxl modules are working as I was testing them with lcm lora (it works with lcm btw!) Just in case, let me know if you can inference with an xl module. Thanks in advance.

I've used the SDXL modules (plus I also tried the ones I made.

**Comment by willpnelson** [comment]
I only have SDXL 1.0 models

**Comment by FizzleDorf** [comment]
Thanks for the input guys. I'm looking into it.

**Comment by onefish51** [comment]
Having the same issue:

**Comment by styler00dollar** [comment]
I have the same error. I want to use sd1.5 and tried `v1_unet_64_1024.so`, `v1_vae_64_1024.so` and `v1_vae_encode_64_1024.so`, but I get:
```
model_interface.cu:122: Error: Called SetConstant on time_embed_0_weight but can't find in either bound or unbound constant set
```

**Comment by nidefawl** [comment]
I am getting the same error with both SD15 and SDXL

**Comment by injet-zhou** [comment]
Same issue here, any update?
