### ISSUE TITLE
Can't install on windows: No module named '_distutils_hack'

### ISSUE THREAD

**Issue by DmytroSokhach** [FizzleDorf/ComfyUI-AIT#13]
After extracting and navigating into ait_windows/python
**python setup.py bdist_wheel** fails with:
```Powershell
(venv) PS D:\Dev\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI-AIT\compile\ait_windows\python> python setup.py bdist_wheel
Traceback (most recent call last):
  File "D:\Dev\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI-AIT\compile\ait_windows\python\setup.py", line 36, in <module>
    from setuptools import find_packages, setup
  File "D:\Dev\StabilityMatrix\Packages\ComfyUI\venv\lib\site-packages\setuptools\__init__.py", line 7, in <module>
    import _distutils_hack.override  # noqa: F401
ModuleNotFoundError: No module named '_distutils_hack'
```

Double checked to install `pip install -U pip setuptools` but doesn't help, still same error.
Please assist.

**Comment by DmytroSokhach** [comment]
Ouch! Year ago opened. Since that I'm using StabilityMatrix to install and run ComfyUI.

**Comment by 44kitcaliber** [comment]
downgrading setuptools fixed it for me.
`pip install setuptools==59.8.0`
