### ISSUE TITLE
ModuleNotFoundError: No module named 'aitemplate'

### ISSUE THREAD

**Issue by sborys-ai** [FizzleDorf/ComfyUI-AIT#2]
Traceback (most recent call last):
  File "/mnt/HDD_1Tb/SDXL/ComfyUI/nodes.py", line 1734, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/HDD_1Tb/SDXL/ComfyUI/custom_nodes/ComfyUI-AIT/__init__.py", line 1, in <module>
    from .ait_load import AIT_Unet_Loader
  File "/mnt/HDD_1Tb/SDXL/ComfyUI/custom_nodes/ComfyUI-AIT/ait_load.py", line 35, in <module>
    from aitemplate.compiler import Model
ModuleNotFoundError: No module named 'aitemplate'

**Comment by FizzleDorf** [comment]
apologies. It is a crucial dependancy. please follow the instructions [here](https://github.com/facebookincubator/AITemplate#installation) I will update the README shortly.

**Comment by FizzleDorf** [comment]
I've added the instructions to the README.txt
