### ISSUE TITLE
ModuleNotFoundError: No module named 'aitemplate'

### ISSUE THREAD

**Issue by willpnelson** [FizzleDorf/ComfyUI-AIT#9]
Traceback (most recent call last):
  File "D:\stable_diffusion\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\stable_diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AIT\__init__.py", line 1, in <module>
    from .ait_load import AIT_Unet_Loader #, AIT_VAE_Encode_Loader
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\stable_diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AIT\ait_load.py", line 35, in <module>
    from aitemplate.compiler import Model
ModuleNotFoundError: No module named 'aitemplate'

Going crazy with this. AITemplate is installed.  For ComfyUI-AIT, I applied the patch to the comfyui root (had to use --reject --whitespace=fx).  I tried this on Python 3.10, 3.11, and 3.12.  Any suggestions?  Thanks.

**Comment by FizzleDorf** [comment]
I've added the instructions to the README.txt
